name = "vidload"
compatibility_date = "2024-01-01"

# Pages build output directory
pages_build_output_dir = "out"

# Environment variables
[vars]
NODE_ENV = "production"
EXPORT_STATIC = "true"

# Production environment configuration
[env.production]
name = "vidload"
[env.production.vars]
NODE_ENV = "production"
EXPORT_STATIC = "true"

# Preview environment configuration
[env.preview]
name = "vidload-preview"
[env.preview.vars]
NODE_ENV = "development"
EXPORT_STATIC = "true"
